# Eager API Tensorflow

## What is Tensorflow's Eager API

Eager execution is an imperative, define-by-run interface where operations are executed immediately as they are called from Python. This makes it easier to get started with TensorFlow, and can make research and development more intuitive. A vast majority of the TensorFlow API remains the same whether eager execution is enabled or not.  
The benefits of eager execution include:

   - Fast debugging with immediate run-time errors and integration with Python tools
   - Support for dynamic models using easy-to-use Python control flow
   - Strong support for custom and higher-order gradients
   - Almost all of the available TensorFlow operations

More info: https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html

In [1]:
from __future__ import absolute_import, division, print_function
import numpy as np
import tensorflow as tf

In [2]:
## Set eager_execution 
tf.enable_eager_execution()
tfe = tf.contrib.eager

In [14]:
## Define constant ops
a = tf.constant(2)
b = tf.constant(3)

print("We can now see the exact values of a and b without running session - ")
print(a.__int__())
print(b.__int__())


We can now see the exact values of a and b without running session - 
2
3


In [16]:
## Running the operation without tf.Session()

print("a+b : ", (a+b).__int__())
print("a*b : ", (a*b).__int__())

a+b :  5
a*b :  6


In [28]:
## Tensorflow eager-tensors are compatible with numpy ndarrays

a = tf.constant([[2.0, 1.0], 
                 [1.0, 0.0]], dtype=tf.float32)
print("Tensor a:\n", a.__str__())
b = tf.constant([[3.0, 0.0],
                 [5.0, 1.0]], dtype=np.float32)
print("Tensor b:\n", b.__str__())

Tensor a:
 tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
Tensor b:
 tf.Tensor(
[[3. 0.]
 [5. 1.]], shape=(2, 2), dtype=float32)


In [30]:
print("a+b: ", (a+b).__str__())
print("a.b: ", (a*b).__str__())  ## element to element multiplication
print("a*b: ", tf.matmul(a,b).__str__())

a+b:  tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
a.b:  tf.Tensor(
[[6. 0.]
 [5. 0.]], shape=(2, 2), dtype=float32)
a*b:  tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
